// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:call_memo/data/local/adapters/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsAdapter());
    registerAdapter(CallEventAdapter());
    registerAdapter(CallRecordAdapter());
    registerAdapter(NoteAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsAdapter());
    registerAdapter(CallEventAdapter());
    registerAdapter(CallRecordAdapter());
    registerAdapter(NoteAdapter());
  }
}
